git: 
    depth: 1

language: objective-c

before_script:
    - brew update
    - brew install ant
    - brew install adobe-air-sdk
    - mkdir -p /usr/local/opt/adobe-air-sdk/libexec/frameworks/libs/player/11.1/
    - cp -f /usr/local/opt/adobe-air-sdk/libexec/frameworks/libs/player/14.0/playerglobal.swc /usr/local/opt/adobe-air-sdk/libexec/frameworks/libs/player/11.1/
    - "export AIR_HOME=/usr/local/opt/adobe-air-sdk/libexec"

script:
    - cd starling/build/ant && ant -DFLEX_HOME=/usr/local/opt/adobe-air-sdk/libexec